version: '3.7'

services:
  app:
    container_name: app
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env.development
    networks:
      - webnet
    links:
      - db
    depends_on:
      - db

  db:
    container_name: db
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  webnet:
