export enum NNK_TEAMS {
  BHC = 'BHC',
  CEU = 'CEU',
  GRE = 'GRE',
  MNE = 'MNE',
  SRB = 'SRB',
  VK = 'VK',
}

export enum NNK_DONORS {
  DONORBOX = 'DONORBOX',
  CHOOSE_LOVE = 'CHOOSE LOVE',
  CARITAS = 'CARITAS',
  PENDE = 'PENDE',
  LINEA_D_OMBRA = "LINEA D'OMBRA",
  OSF = 'OSF',
  SEENOTRETTUNG = 'SEENOTRETTUNG',
  FONS = 'FONS',
  FRONTLINE = 'FRONTLINE',
  CATCH = 'CATCH',
  NNK_YABASTA = 'NNK YABASTA',
  NNK_FUND = 'NNK FUND',
  WPA = 'WPA',
  HADAS = 'HADAS',
}

export enum NNK_CURRENCIES {
  BAM = 'BAM',
  DINAR = 'DINAR',
  HRK = 'HRK',
  EURO = 'EURO',
}

export enum NNK_EXPENSES_CATEGORIES {
  Facilities = 'Facilities',
  Supplies = 'Supplies',
  Vehicles = 'Vehicles',
  Food = 'Food',
  NFIs = 'NFIs',
  Health = 'Health',
  Admin_Support = 'Admin Support',
  Comms = 'Comms',
}

export enum NNK_EXPENSES_CONCEPTS {
  Warehouse = 'Warehouse',
  House = 'House',
  Flat = 'Flat',
  Flat_Yabasta = 'Flat Yabasta',
  water_WH_ykb = 'water WH ykb',
  water_WH_extra = 'water WH extra',
  water_House = 'water House',
  water_flat = 'water flat',
  electricity_WH = 'electricity WH',
  electricity_house = 'electricity house',
  electricity_flat = 'electricity flat',
  WiFi_House = 'WiFi House',
  Heating_Yabasta_flat = 'Heating Yabasta flat',
  waste_collection_flat = 'waste collection flat',
  waste_collection_house = 'waste collection house',
  furniture = 'furniture',
  furniture_Yabasta_flat = 'furniture Yabasta flat',
  toolbox_hardware = 'toolbox + hardware (plastic bags, bulbs, gloves...)',
  NNK_basket = 'NNK basket (clean + food)',
  Yabasta_basket = 'Yabasta basket (clean + food)',
  purchase = 'purchase',
  renting = 'renting',
  fuel = 'fuel',
  fuel_health_car = 'fuel health car',
  mechanic_check_fixing = 'mechanic_check / fixing',
  mechanic_check_fixing_health_car = 'mechanic_check / fixing health car',
  insurances = 'insurances',
  emergency_kit = 'emergency kit',
  others = 'others (toll, parking)',
  ingredients_meals = 'ingredients / meals',
  extra_food_packs = 'extra food packs',
  kitchenware = 'kitchenware',
  coffee_interview = 'coffee interview (reporters)',
  shipment_importation = 'shipment (importation)',
  clothes = 'clothes',
  shoes = 'shoes',
  sleeping_bags_blankets = 'sleepingbags / blankets',
  firewood = 'firewood',
  tents_blankets_bags = 'tents/blankets/bags',
  books_pens_leisure = 'books_/_pens_/_leisure',
  first_aid_box = 'first_aid_box',
  laundry = 'laundry (service, soap…)',
  shower = 'shower (gas, tanks…)',
  hygiene_underwear = 'hygiene / underwear',
  treatment_costs_covered_by_ykb = 'treatment costs covered by ykb',
  treatment_costs_covered_by_nnk = 'treatment costs covered by nnk',
  extra_treatment_costs = 'extra treatment costs',
  transport_for_patients = 'transport for patients',
  covid_tests_nnk = 'covid tests nnk',
  covid_tests_yabasta = 'covid tests yabasta',
  Lawyer = 'Lawyer',
  accountant = 'accountant',
  fees_fines = 'fees / fines',
  white_cards = 'white cards',
  bank_comission = 'bank comission',
  psychologist = 'psychologist',
  laptop_IT_service = 'laptop / IT service',
  stationaries = 'stationaries',
  Print_copy = 'Print & copy',
  Hotline_phone_sim_credit = 'Hotline phone / sim / credit',
  SIM_Yabasta = 'SIM Yabasta',
  electricity_Bosnian_family = 'electricity Bosnian family',
}
