name: prettier

on:
  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18]

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: npm install
        run: npm ci

      - name: get differences
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/*.js
            **/*.css
            **/*.json
            **/*.ts
            **/*.md
            **/*.yml

      - name: verify the files that changed
        if: ${{ env.GIT_DIFF_FILTERED != '' }}
        run: echo "${{env.GIT_DIFF_FILTERED}}" | xargs npm run format:check
